name: devnology
env: node
build:
  builder: 'node:16'
  steps:
    - run: npm install
run:
  web: npm start
services:
  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devnology
    ports:
      - '5432:5432'
  app:
    build:
      dockerfile: Dockerfile
    command: npm start
    env:
      DATABASE_URL: postgres://root:password@database:5432/devnology
    depends_on:
      - database
    ports:
      - 8080:8080
